<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>7.1.0.22155</Version>
    <Nullable>enable</Nullable>
    <Company>Andrey Makarov</Company>
    <LangVersion>8.0</LangVersion>
    <GenerateFullPaths>true</GenerateFullPaths>
    <Copyright>Copyright © NonFactors</Copyright>
    <PackageId>MVCGrid.Core.Mvc6</PackageId>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>NonFactors.Mvc.Grid</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType Condition="'$(Configuration)'=='Release'">none</DebugType>
    <AssemblyVersion>7.1.23168.0</AssemblyVersion>
    <FileVersion>7.1.0.22155</FileVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReleaseNotes>Added error handling</PackageReleaseNotes>
    <Authors>NonFactors &amp; Andrey Makarov</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.2.0" />
  </ItemGroup>

</Project>
